export type FeedConfig = {
  id: string;
  title: string;
  url: string;
  description?: string;
  limit?: number;
};

export const FEEDS: FeedConfig[] = [
  // Core esports and business coverage
  {
    id: "ign",
    title: "IGN All",
    url: "https://feeds.ign.com/ign/all",
    description: "Breaking gaming and entertainment coverage from IGN.",
    limit: 15,
  },
  {
    id: "dotesports",
    title: "Dot Esports",
    url: "https://dotesports.com/feed",
    description: "Competitive gaming updates across major esports titles.",
    limit: 15,
  },
  {
    id: "esportsinsider",
    title: "Esports Insider",
    url: "https://esportsinsider.com/feed/",
    description: "Esports business, sponsorship, and event coverage.",
    limit: 15,
  },
  {
    id: "gamesindustry-all",
    title: "GamesIndustry.biz - All Content",
    url: "https://www.gamesindustry.biz/feed",
    description: "Every article published across GamesIndustry.biz.",
    limit: 15,
  },
  {
    id: "gamesindustry-academy",
    title: "GamesIndustry.biz - Academy",
    url: "https://www.gamesindustry.biz/feed/academy",
    description: "Career tips, expert advice, and how-to guides for game makers.",
    limit: 12,
  },
  {
    id: "gamesindustry-data",
    title: "GamesIndustry.biz - Data",
    url: "https://www.gamesindustry.biz/feed/data",
    description: "Charts, sales figures, and market intelligence for the industry.",
    limit: 12,
  },
  {
    id: "gamesindustry-features",
    title: "GamesIndustry.biz - Features",
    url: "https://www.gamesindustry.biz/feed/features",
    description: "Deep dives and long-form reporting on the business of games.",
    limit: 12,
  },
  {
    id: "gamesindustry-news",
    title: "GamesIndustry.biz - News",
    url: "https://www.gamesindustry.biz/feed/news",
    description: "Daily worldwide news for the games business.",
    limit: 15,
  },
  {
    id: "gamesindustry-opinion",
    title: "GamesIndustry.biz - Opinion",
    url: "https://www.gamesindustry.biz/feed/opinion",
    description: "Editorial insights and perspectives from industry voices.",
    limit: 12,
  },
  // Broad gaming coverage supplied list
  {
    id: "kotaku",
    title: "Kotaku",
    url: "https://kotaku.com/rss",
    description: "Kotaku's latest gaming culture news and features.",
    limit: 15,
  },
  {
    id: "vg247",
    title: "VG247",
    url: "https://www.vg247.com/feed",
    description: "VG247 headlines and guides spanning the gaming world.",
    limit: 15,
  },
  {
    id: "gamespot-mashup",
    title: "GameSpot Mashup",
    url: "https://www.gamespot.com/feeds/mashup",
    description: "GameSpot's mashup of news, reviews, and features.",
    limit: 15,
  },
  {
    id: "wolfs-gaming-blog",
    title: "Wolf's Gaming Blog",
    url: "https://wolfsgamingblog.com/feed",
    description: "Indie reviews and opinion from Wolf's Gaming Blog.",
    limit: 12,
  },
  {
    id: "polygon",
    title: "Polygon",
    url: "https://www.polygon.com/rss/index.xml",
    description: "Video game culture, esports, and entertainment analysis.",
    limit: 15,
  },
  {
    id: "dualshockers",
    title: "DualShockers",
    url: "https://www.dualshockers.com/feed",
    description: "Gaming news, reviews, and opinion from DualShockers.",
    limit: 15,
  },
  {
    id: "nvidia-gaming",
    title: "NVIDIA Gaming Blog",
    url: "https://blogs.nvidia.com/blog/category/gaming/feed",
    description: "Gaming updates from the official NVIDIA blog.",
    limit: 10,
  },
  {
    id: "amigaguru",
    title: "AmigaGuru's GamerBlog",
    url: "https://blog.amigaguru.com/feed",
    description: "Retro Amiga gaming news and commentary.",
    limit: 10,
  },
  {
    id: "siliconera",
    title: "Siliconera",
    url: "https://www.siliconera.com/feed",
    description: "Japanese and indie game news from Siliconera.",
    limit: 15,
  },
  {
    id: "playstation-blog",
    title: "PlayStation Blog",
    url: "https://blog.playstation.com/feed",
    description: "Official PlayStation updates and feature stories.",
    limit: 15,
  },
  {
    id: "rockpapershotgun",
    title: "Rock Paper Shotgun",
    url: "https://www.rockpapershotgun.com/feed",
    description: "PC gaming news and reviews from Rock Paper Shotgun.",
    limit: 15,
  },
  {
    id: "operationsports",
    title: "Operation Sports",
    url: "https://operationsports.com/feed",
    description: "Sports gaming news, reviews, and community coverage.",
    limit: 12,
  },
  {
    id: "gamesfuze",
    title: "Games Fuze",
    url: "https://gamesfuze.com/feed",
    description: "Guides, leaks, and updates across popular games.",
    limit: 12,
  },
  {
    id: "attack-of-the-fanboy",
    title: "Attack of the Fanboy",
    url: "https://attackofthefanboy.com/feed",
    description: "News, reviews, and guides from Attack of the Fanboy.",
    limit: 15,
  },
  {
    id: "gamehype",
    title: "GameHype",
    url: "https://gamehype.co.uk/feed",
    description: "UK-based gaming news, reviews, and previews.",
    limit: 12,
  },
  {
    id: "intoindiegames",
    title: "Into Indie Games",
    url: "https://intoindiegames.com/feed",
    description: "Spotlighting indie game development and releases.",
    limit: 12,
  },
  {
    id: "shacknews",
    title: "Shacknews",
    url: "https://www.shacknews.com/feed/rss",
    description: "Shacknews coverage of games, tech, and esports.",
    limit: 15,
  },
  {
    id: "alphabetagamer",
    title: "Alpha Beta Gamer",
    url: "https://www.alphabetagamer.com/feed",
    description: "Indie alpha and beta test news from Alpha Beta Gamer.",
    limit: 12,
  },
  {
    id: "mp3sandnpcs",
    title: "MP3s & NPCs",
    url: "https://mp3sandnpcs.com/home?format=rss",
    description: "Gaming culture and music stories from MP3s & NPCs.",
    limit: 10,
  },
  {
    id: "cowded",
    title: "Cowded",
    url: "https://cowded.com/feed",
    description: "Gaming news, guides, and esports coverage from Cowded.",
    limit: 12,
  },
  {
    id: "gematsu",
    title: "Gematsu",
    url: "https://www.gematsu.com/feed",
    description: "Japanese video game news and updates from Gematsu.",
    limit: 15,
  },
  {
    id: "gamingstudio4u",
    title: "Gaming Studio 4U",
    url: "https://gamingstudio4u.blogspot.com/feeds/posts/default",
    description: "Gaming Studio 4U blog updates.",
    limit: 10,
  },
  {
    id: "arpegi",
    title: "Arpegi",
    url: "https://arpegi.wordpress.com/feed",
    description: "Gaming reviews, previews, and personal reflections.",
    limit: 10,
  },
  {
    id: "newgamenetwork",
    title: "New Game Network",
    url: "https://feeds.feedburner.com/newgamenetwork",
    description: "New Game Network reviews and features.",
    limit: 12,
  },
  {
    id: "pcgamer",
    title: "PC Gamer",
    url: "https://www.pcgamer.com/rss",
    description: "PC Gamer's latest news, reviews, and hardware coverage.",
    limit: 15,
  },
  {
    id: "sassygamers",
    title: "SassyGamers",
    url: "https://sassygamers.com/feed",
    description: "Gaming editorials, reviews, and streaming guides.",
    limit: 10,
  },
  {
    id: "prima-games",
    title: "Prima Games",
    url: "https://primagames.com/feed",
    description: "Official Prima Games guides and news.",
    limit: 15,
  },
  {
    id: "playstation-lifestyle",
    title: "PlayStation LifeStyle",
    url: "https://www.playstationlifestyle.net/feed",
    description: "PlayStation news, reviews, and features.",
    limit: 15,
  },
  {
    id: "purenintendo",
    title: "Pure Nintendo",
    url: "https://purenintendo.com/feed",
    description: "Nintendo news, reviews, and magazine updates.",
    limit: 15,
  },
  {
    id: "sixtyfps",
    title: "60FPS",
    url: "https://60fps.in/feed",
    description: "Insights and opinion on the gaming industry.",
    limit: 10,
  },
  {
    id: "techraptor",
    title: "TechRaptor",
    url: "https://techraptor.net/news/feed",
    description: "TechRaptor gaming news and tech coverage.",
    limit: 15,
  },
  {
    id: "monstervine",
    title: "MonsterVine",
    url: "https://monstervine.com/feed",
    description: "MonsterVine reviews and articles.",
    limit: 12,
  },
  {
    id: "massivelyop",
    title: "Massively Overpowered",
    url: "https://massivelyop.com/feed",
    description: "MMO news and analysis from MassivelyOP.",
    limit: 15,
  },
  {
    id: "thexboxhub",
    title: "TheXboxHub",
    url: "https://www.thexboxhub.com/feed",
    description: "Xbox news, reviews, and opinion.",
    limit: 12,
  },
  {
    id: "gamingbolt",
    title: "GamingBolt",
    url: "https://feeds.feedburner.com/gamingbolt",
    description: "GamingBolt coverage of industry news and reviews.",
    limit: 15,
  },
  {
    id: "indie-retro-news",
    title: "Indie Retro News",
    url: "https://indieretronews.com/feeds/posts/default",
    description: "Retro and indie gaming news.",
    limit: 12,
  },
  {
    id: "whatifgaming",
    title: "WhatIfGaming",
    url: "https://whatifgaming.com/feed",
    description: "Guides, reviews, and opinion from WhatIfGaming.",
    limit: 12,
  },
  {
    id: "gamingonlinux",
    title: "GamingOnLinux",
    url: "https://www.gamingonlinux.com/article_rss.php",
    description: "Linux gaming news and updates.",
    limit: 12,
  },
  {
    id: "gamezebo",
    title: "Gamezebo",
    url: "https://www.gamezebo.com/feed",
    description: "Mobile, PC, and console reviews from Gamezebo.",
    limit: 15,
  },
  {
    id: "thesixthaxis",
    title: "TheSixthAxis",
    url: "https://www.thesixthaxis.com/feed",
    description: "PlayStation, Xbox, and Nintendo coverage from TSA.",
    limit: 12,
  },
  {
    id: "gonintendo",
    title: "GoNintendo",
    url: "https://feedpress.me/gonintendo",
    description: "Nintendo news, rumors, and community updates.",
    limit: 15,
  },
  {
    id: "nitchigamer",
    title: "NitchiGamer",
    url: "https://nitchigamer.com/feed/?post_type=post",
    description: "Curated indie and niche gaming coverage.",
    limit: 10,
  },
  {
    id: "eightbitdigi",
    title: "8Bit/Digi",
    url: "https://8bitdigi.com/feed",
    description: "Bay Area gaming news and reviews.",
    limit: 10,
  },
  {
    id: "superjump",
    title: "SUPERJUMP",
    url: "https://superjumpmagazine.com/rss",
    description: "Longform stories and spotlights from SUPERJUMP Magazine.",
    limit: 12,
  },
  {
    id: "nintendofuse",
    title: "NintendoFuse",
    url: "https://nintendofuse.com/feed",
    description: "Nintendo news, podcasts, and reviews.",
    limit: 12,
  },
  {
    id: "nichegamer",
    title: "Niche Gamer",
    url: "https://nichegamer.com/feed",
    description: "Japanese and niche gaming coverage.",
    limit: 15,
  },
  {
    id: "spacegamejunkie",
    title: "Space Game Junkie",
    url: "https://spacegamejunkie.com/feed",
    description: "Space game news, reviews, and podcasts.",
    limit: 10,
  },
  {
    id: "thisislevelup",
    title: "This Is Level Up",
    url: "https://thisislevelup.net/feed",
    description: "Gaming news, reviews, and esports coverage.",
    limit: 10,
  },
  {
    id: "classic-games",
    title: "Classic-Games.net",
    url: "https://classic-games.net/feed",
    description: "Classic and retro game reviews.",
    limit: 10,
  },
  {
    id: "pcgamesn",
    title: "PCGamesN",
    url: "https://www.pcgamesn.com/mainrss.xml",
    description: "PCGamesN news, guides, and hardware stories.",
    limit: 15,
  },
  {
    id: "egamers-io",
    title: "eGamers.io",
    url: "https://egamers.io/feed",
    description: "Blockchain gaming and metaverse coverage.",
    limit: 10,
  },
  {
    id: "megavisions",
    title: "Mega Visions",
    url: "https://megavisions.net/feed",
    description: "Retro and modern gaming news from Mega Visions.",
    limit: 12,
  },
  {
    id: "gaminginstincts",
    title: "Gaming Instincts",
    url: "https://gaminginstincts.com/feed",
    description: "Gaming Instincts news, reviews, and guides.",
    limit: 12,
  },
  {
    id: "escapist-magazine",
    title: "The Escapist",
    url: "https://www.escapistmagazine.com/feed",
    description: "News and opinion from The Escapist Magazine.",
    limit: 15,
  },
  {
    id: "invision-community",
    title: "Invision Game Community",
    url: "https://invisioncommunity.co.uk/feed",
    description: "Invision Game Community press releases and articles.",
    limit: 12,
  },
  {
    id: "adventuregamers",
    title: "Adventure Gamers",
    url: "https://adventuregamers.com/rss",
    description: "Adventure game news and reviews.",
    limit: 12,
  },
  {
    id: "nintendosmash",
    title: "Nintendo Smash",
    url: "https://nintendosmash.com/feed",
    description: "Nintendo Smash news and guides.",
    limit: 12,
  },
  {
    id: "centurion-report",
    title: "The Centurion Report",
    url: "https://thecenturionreport.com/feed",
    description: "Guides and news from The Centurion Report.",
    limit: 12,
  },
  {
    id: "droidgamers",
    title: "DroidGamers",
    url: "https://feeds.feedburner.com/DroidGamers",
    description: "Android gaming news and reviews from DroidGamers.",
    limit: 12,
  },
  {
    id: "nintendoeverything",
    title: "Nintendo Everything",
    url: "https://nintendoeverything.com/feed",
    description: "Nintendo Everything news and coverage.",
    limit: 15,
  },
  {
    id: "gamedeveloper",
    title: "Game Developer",
    url: "https://gamedeveloper.com/rss.xml",
    description: "Game Developer industry news and analysis.",
    limit: 15,
  },
  {
    id: "videogamer",
    title: "VideoGamer",
    url: "https://www.videogamer.com/feed",
    description: "VideoGamer.com news and reviews.",
    limit: 12,
  },
  {
    id: "videochums",
    title: "Video Chums",
    url: "https://videochums.com/feed.rss",
    description: "Video Chums reviews and features.",
    limit: 12,
  },
  {
    id: "thetechgame",
    title: "TheTechGame",
    url: "https://www.thetechgame.com/rss.php",
    description: "TheTechGame news and community posts.",
    limit: 12,
  },
  {
    id: "unigamesity",
    title: "Unigamesity",
    url: "https://unigamesity.com/feed",
    description: "Gaming news and guides from Unigamesity.",
    limit: 12,
  },
  {
    id: "playerauctions-blog",
    title: "PlayerAuctions Blog",
    url: "https://blog.playerauctions.com/feed",
    description: "PlayerAuctions MMO and gaming marketplace articles.",
    limit: 12,
  },
  {
    id: "consolecreatures",
    title: "Console Creatures",
    url: "https://consolecreatures.com/feed",
    description: "Console Creatures news and reviews.",
    limit: 12,
  },
  {
    id: "gnomestew",
    title: "Gnome Stew",
    url: "https://gnomestew.com/feed",
    description: "Tabletop RPG advice from Gnome Stew.",
    limit: 10,
  },
  {
    id: "gamingdebugged",
    title: "Gaming Debugged",
    url: "https://gamingdebugged.com/feed",
    description: "Gaming Debugged news, tutorials, and dev stories.",
    limit: 12,
  },
  {
    id: "toomuchgaming",
    title: "Too Much Gaming",
    url: "https://toomuchgaming.net/blog-news?format=rss",
    description: "Philippines-based gaming news and blogs.",
    limit: 10,
  },
  {
    id: "nintendolife",
    title: "Nintendo Life",
    url: "https://www.nintendolife.com/feeds/latest",
    description: "Nintendo Life news, reviews, and features.",
    limit: 15,
  },
  {
    id: "gamersheroes",
    title: "GamersHeroes",
    url: "https://www.gamersheroes.com/feed",
    description: "GamersHeroes news, reviews, and guides.",
    limit: 12,
  },
  {
    id: "joyfreak",
    title: "JoyFreak Forums",
    url: "https://joyfreak.com/forums/-/index.rss",
    description: "Community discussions from JoyFreak forums.",
    limit: 10,
  },
  {
    id: "mynintendonews",
    title: "My Nintendo News",
    url: "https://mynintendonews.com/feed",
    description: "Nintendo news, rumors, and updates.",
    limit: 15,
  },
  {
    id: "gtogg",
    title: "GTogg",
    url: "https://gtogg.com/rss",
    description: "GTogg gaming news and reviews.",
    limit: 12,
  },
  {
    id: "cgmagonline",
    title: "CGMagazine",
    url: "https://www.cgmagonline.com/feed",
    description: "CGMagazine games, tech, and pop culture news.",
    limit: 12,
  },
  {
    id: "n4g",
    title: "N4G",
    url: "https://n4g.com/rss/news?channel=",
    description: "Community-curated gaming news from N4G.",
    limit: 15,
  },
  {
    id: "gamehaunt",
    title: "GameHaunt",
    url: "https://gamehaunt.com/feed",
    description: "Gaming news and reviews from GameHaunt.",
    limit: 12,
  },
  {
    id: "pushsquare",
    title: "Push Square",
    url: "https://www.pushsquare.com/feeds/latest",
    description: "PlayStation news and reviews from Push Square.",
    limit: 15,
  },
  {
    id: "gamesroid",
    title: "Gamesroid",
    url: "https://gamesroid.com/feed",
    description: "Gamesroid gaming news and walkthroughs.",
    limit: 12,
  },
  {
    id: "quretic",
    title: "Quretic",
    url: "https://quretic.com/feed",
    description: "Gaming reviews, culture, and esports stories.",
    limit: 10,
  },
  {
    id: "twinfinite",
    title: "Twinfinite",
    url: "https://twinfinite.net/feed",
    description: "Gaming news, guides, and opinion from Twinfinite.",
    limit: 15,
  },
  {
    id: "lastwordongaming",
    title: "Last Word on Gaming",
    url: "https://lastwordongaming.com/feed",
    description: "Gaming insights, reviews, and esports coverage.",
    limit: 12,
  },
  {
    id: "vgamerz",
    title: "VGamerZ",
    url: "https://vgamerz.com/feed",
    description: "Gaming news and opinion from VGamerZ.",
    limit: 12,
  },
  {
    id: "tryhardguides",
    title: "Try Hard Guides",
    url: "https://tryhardguides.com/feed",
    description: "Guides and news for popular games.",
    limit: 15,
  },
  {
    id: "finding-god-in-games",
    title: "Finding God in the World of Video Games",
    url: "https://findinggodintheworldofvideogames.com/feed",
    description: "Faith-focused reflections on video games.",
    limit: 10,
  },
  {
    id: "gamecritics",
    title: "GameCritics",
    url: "https://gamecritics.com/feed",
    description: "Thoughtful game reviews and editorials.",
    limit: 12,
  },
  {
    id: "three60fov",
    title: "360fov",
    url: "https://360fov.net/feed",
    description: "360fov gaming news and commentary.",
    limit: 10,
  },
  {
    id: "xbox-wire",
    title: "Xbox Wire",
    url: "https://news.xbox.com/en-us/feed",
    description: "Official Xbox news and announcements.",
    limit: 15,
  },
  {
    id: "indiegamesplus",
    title: "Indie Games Plus",
    url: "https://indiegamesplus.com/feed",
    description: "Indie games news and reviews.",
    limit: 12,
  },
  {
    id: "idev-games",
    title: "iDev Games",
    url: "https://idev.games/rss-feed.xml",
    description: "iDev indie game development updates.",
    limit: 10,
  },
  {
    id: "gamingyeeter",
    title: "Gaming Yeeter",
    url: "https://gamingyeeter.com/feed",
    description: "Gaming Yeeter news and reviews.",
    limit: 10,
  },
  {
    id: "gameslushpile",
    title: "Game Slush Pile",
    url: "https://gameslushpile.com/feed",
    description: "Highlighting overlooked games and hidden gems.",
    limit: 10,
  },
  {
    id: "hotyhs",
    title: "HotYHS",
    url: "https://hotyhs.wordpress.com/feed",
    description: "HotYHS gaming blog updates.",
    limit: 10,
  },
  {
    id: "buycheapps4games",
    title: "BuyCheApps4Games",
    url: "https://buycheapps4games.blogspot.com/feeds/posts/default",
    description: "BuyCheApps4Games blog posts.",
    limit: 10,
  },
];

export function getFeedConfigById(id: string): FeedConfig | undefined {
  return FEEDS.find((feed) => feed.id === id);
}

export function getAllFeeds(): FeedConfig[] {
  return FEEDS;
}
